version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install jest
      - run: npm install front-matter
      - run: npm test